# Generated by Django 2.2.1 on 2019-06-06 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_auto_20190606_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 7, 17, 50, 557702, tzinfo=utc)),
        ),
    ]
